### ISSUE TITLE
[TASK] Story #28: Implement "My Listings" display

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#116]
This is preliminary. Subject to change.

TODO: This ticket needs to be updated.  The "My listings" page belongs to the Login/Logout epic. The Edit/Delete functionality belongs to the Modification epic. 

### Associated User Story: 
#28 
### Task Description:
Create an area of the application where users can view listings associated with their account
### Dependencies:
- Requires an association between listings and user accounts.
### Acceptance Criteria:
- One big dev task for now. Probably a good idea to split into smaller chunks. 
- [ ] If (and only if) a user is logged in, display a button on the top bar which says "My Listings" that leads them to (maybe?):
  - A different page which says "my listings" at the top, and shows a list of listings associated with their account on the right side, in a format very similar to how we plan the main page to be. (In fact, we could probably just use the same components, but just with the list containing only their listings and with the style being different enough so that they know they're looking at their own listings)
- [ ] If user tries to go to that page without being logged in, they should see access denied or some other reasonable error page (probably more of a back end thing, but worthwhile to ensure)
- [ ] The mini-view of listings on the "My Listings" page should either have: 
  - 3 dots in the top right corner, which upon clicking, show options to "Edit" and "Delete"
  - Or, Have 2 buttons on each mini-ad (maybe the mini-ads can be larger) for Edit and Delete
  - These 2 buttons are being included in this dev task, because it will save time to consider these buttons in page design
  - The buttons should have no functionality. That will be implemented in another dev task.
