### ISSUE TITLE
Modifying the rental properties

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#118]
Finished these three user stories
- [ ] As a landlord, I want to be able to edit the details of my rental property listing
- [ ] As a landlord, I want to be able to specify whether my listing has been rented out yet.
- [ ] As a landlord, I want to be able to delete my own rental property listing.
