### ISSUE TITLE
[Task] Story #31 Search for properties based on price range

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#121]
### Associated User Story: 
User story #31 

### Task Description:
- [ ] Implement a search bar where user can input minimum and maximum price
- [ ] Add a "Search" button that runs the function to gets the listings within the min and max price
- [ ] Update original listing array, so that apartments within the price range get displayed

### Dependencies:
Depend on user story: #23 , which is responsible for displaying the listings

### Acceptance Criteria:
- [ ] If user can input the price in min and max field
- [ ] If Search button invokes the function that find the listings within the price range
- [ ] If listings within the price range is displayed
