### ISSUE TITLE
[Task] Story #32 Search for listings based on number of bedrooms

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#122]
### Associated User Story: 
This is associated with user story #32  

### Task Description:
- [ ] Implement search field where user choose number of bedrooms
- [ ] Implement search function that returns listing with # of bedrooms from input
- [ ] Implement the mechanism that substitutes original listing array with search result
- [ ] Potential Redux setup

### Dependencies:
Null

### Acceptance Criteria:
- [ ] If the user is able to specify number of bedrooms in search field in "Select" component
- [ ] The function does return listings with number of bedrooms as user specified
- [ ] Original listing array get substituted with new array, listings with specific number of bedrooms get displayed
