### ISSUE TITLE
[Task] Story #33 Search for listings based on keywords

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#123]
### Associated User Story: 
This is associated with user story #33 

### Task Description:
- [ ] Implement search field where user can input keywords they want to search for
- [ ] Implement search function that returns listing with keywords in it
- [ ] Implement the mechanism that substitutes original listing array with search result
- [ ] Potential Redux setup

### Dependencies:
Null

### Acceptance Criteria:
- [ ] If the user is able to specify keywords in field
- [ ] The function does return listings with keywords as user specified
- [ ] Original listing array get substituted with qualified listings, listings with keywords get displayed
