### ISSUE TITLE
[Task] Story #34 Search for listings based on cities

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#124]
### Associated User Story: 
This is associated with user story #34 

### Task Description:
- [ ] Implement search field where user can input cities they want to search
- [ ] Implement search function that returns listing with cities user specified from input
- [ ] Implement the mechanism that substitutes original listing array with search result
- [ ] Potential Redux setup

### Dependencies:
Null

### Acceptance Criteria:
- [ ] If the user is able to specify city in search field
- [ ] The function does return listings with specific city as user specified
- [ ] Original listing array get substituted with new array, listings with specific city get displayed
