### ISSUE TITLE
[TASK] Story #29: Add UI to mark listings as rented 

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#125]
Preliminary.

### Task Description:
For users to mark their listings as rented, they need a button to be able to do so. 
We have some options in terms of how to implement this:
- It could be implemented by placing a "mark as sold" button on a mini-ad on the My Listings page (see #116) 
- It could be placed on a "three dots" menu on the top-right corner of mini-ads on the My Listings page
  - I prefer this solution. 
- It could be incorporated in to the "Edit Listing" modal (in addition to one of the two above options)
### Dependencies:
This is dependent on #116. 
### Acceptance Criteria:
- [ ] Landlords can mark and unmark their own listings as rented (with corresponding messages sent to back end)
- [ ] Other users should not be able to see a listing marked as rented on the main page
- [ ] If a listing is marked as rented, a landlord should still be able to see it on their My Listings page. 
- [ ] There should be some UI changes on listings if they are marked as rented. (have a big "sold" icon overlaying the picture? Turn the background of the mini-version a greyish colour?)
