### ISSUE TITLE
[Task] Story #119 Posting a question in Q&A section, frontend part

### ISSUE THREAD

**Issue by Mik3Qiao** [jcsnorlax97/rentr#126]
### Associated User Story: 
This is associated with user story #119 

### Task Description:
- [ ] Implement a button, that allows user to ask questions about a listing
- [ ] Implement the title area for a user to ask questions
- [ ] Implement the content area for a user to ask a question
- [ ] Implement a submit button when a user's finished their question
- [ ] Update listing page when users submit their questions

### Dependencies:
Null

### Acceptance Criteria:
- [ ] User should be able to see question title and question content when they click on the button to post a question
- [ ] Title area should be modifiable and should record user's input
- [ ] Content area should also be modifiable and should record user's input
- [ ] Submit button should add the question user asked to Q&A section of a specific listing
- [ ] The listing should show the question asked by all users
