### ISSUE TITLE
[TASK] Story #28: Implement a PUT route to update all the fields in a listing

### ISSUE THREAD

**Issue by AzizulHakim96** [jcsnorlax97/rentr#132]
### Associated User Story:
#28

### Task Description:
- This task aims to implement the update functionality by creating a `PUT/api/v1/listing/:id` route.
- Route: `/api/v1/user/:id/listing/:lid`
- Areas that involve updates:
   - `/api` folder (**required**)
   - `/controllers` folder (**required**)
   - `/service` folder (**required**)
   - `/dao` folder (**required**)
- This task will also implement unit test in `/service/listing.test.js` folder

### Dependencies:
N/A

### Acceptance Criteria:
- This task will successfully update the following fields:
	- [x] title
	- [x] price
	- [x] number of bedrooms
	- [x] number of bathrooms
	- [x] description
	- [x] Whether it allows pets
	- [x] Whether it has parking
	- [x] Whether it has laundry
	- [x] Photos
