### ISSUE TITLE
[TASK] Story #119, #120: QnA DB Storage

### ISSUE THREAD

**Issue by RonnieDsouza** [jcsnorlax97/rentr#136]
### Associated User Story: 
#119  As a tenant, I can publicly post a question about a particular listing so that I can save time for other renters. 
#120 As a user, I can publicly answer a question about a particular listing.
### Task Description:
Implement storage capabilities for the QnA section Questions and Answers.
Each Q/A will have the following fields within the same 'Comments' table: 
- Comment (string)
- UserID
- ListingID
- ChainID
- CommentID (int)
- [ ] Create a Questions Table in the DB.
- [ ] Add the above fields to the table
- [ ] Primary Key: ListingID + ChainID + CommentID
### Dependencies:
N/A
### Acceptance Criteria:
- [ ] All fields are present 
- [ ] Can be initialised with the right data types
