### ISSUE TITLE
[TASK] Story #119, #120: POST api/v1/comment

### ISSUE THREAD

**Issue by RonnieDsouza** [jcsnorlax97/rentr#137]
### Associated User Story: 
#119 As a tenant, I can publicly post a question about a particular listing so that I can save time for other renters. 
#120 As a user, I can publicly answer a question about a particular listing.

### Task Description:
Implement a post route for commenting on a particular listing. (Comment refers to the posting of both Questions and Answers.)
The route will implement the following fields: 
- [ ] Comment (string)
- [ ] UserID
- [ ] ListingID
- [ ] ChainID
- [ ] CommentID
- [ ] Add new methods in the following folders:
   - [ ] `/api` folder (**required**)
   - [ ] `/controllers` folder (**required**)
   - [ ] `/service` folder (**required**)
   - [ ] `/dao` folder (**required**)
   - [ ] `/dto` folder (**required**)
   - [ ] `/migrations` folder (**required**)
- [ ] Use user validating middleware to make sure a logged in user is posting a comment.
- [ ] has string validating middleware to protect against SQL injections. 
### Dependencies:
- #136 QnA DB Storage
### Acceptance Criteria:
- [ ] Comments appear in the DB with all the fields having the right values
- [ ] Empty comments aren't accepted
- [ ] Users must be logged in to access this post route.
