### ISSUE TITLE
[TASK] Story #119, #120: GET api/v1/comment

### ISSUE THREAD

**Issue by RonnieDsouza** [jcsnorlax97/rentr#138]
### Associated User Story: 
#119 As a tenant, I can publicly post a question about a particular listing so that I can save time for other renters. 
#120 As a user, I can publicly answer a question about a particular listing.  

### Task Description:
Implement a get route for displaying the existing comments on a particular listing. (Comment refers to the posting of both Questions and Answers.)
The route will return the following fields for any given ListingID: 
- Comment (string)
- UserID
- ChainID
- CommentID
- This GET request returns all the comments on a listing.
- This returns a list of arrays. Each array is a comment chain. This is in JSON format. 
- [x] Add new methods in the following folders:
   - [x] `/api` folder (**required**)
   - [x] `/controllers` folder (**required**)
   - [x] `/service` folder (**required**)
   - [x] `/dao` folder (**required**)
### Dependencies:
- #136 QnA DB Storage
### Acceptance Criteria:
- [ ] Comments appear in the website with all the fields having the right values
  - Justin's comment: this should be belonging to front-end.
