### ISSUE TITLE
[TASK] Story #31 #32: Filtering GET /api/v1/listing results (1) - Ranges

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#140]
### Associated User Story: 
#31, #32

### Task Description:
- This task aims to add the filtering functionality for `GET /api/v1/listing` route. 
- This task focuses on the following fields:
   - [x] price (min vs max)
   - [x] num_bedroom (min vs max)
   - [x] num_bathroom (min vs max)
- Subtasks:
   - [x] Add `validateQueryString` middleware which would validate & transform the query string into a json object (or any other format TBD) before being used by the `getAllListings` in ListingController.
   - [x] Update `getAllListings` in ListingController such that it passes query string to ListingService.
   - [x] (Optional) Validate the transformed query string in Service layer to ensure we're querying DB in DAO layer using valid query string.
   - [x] Update `getAllListings()` in ListingDao to ask DB do filtering for us via SQL queries.

### Dependencies:
N/A

### Acceptance Criteria:
- [x] Able to filter listings via price range correctly when adding query string to the `GET /api/v1/listing` request.
- [x] Able to filter listings via num_bedroom range correctly when adding query string to the `GET /api/v1/listing` request.
- [x] Able to filter listings via num_bathroom range correctly when adding query string to the `GET /api/v1/listing` request.
- [x] Able to filter listings via the combination of all three fields correctly when adding query string to the `GET /api/v1/listing` request.

**Comment by jcsnorlax97** [comment]
Associated PR has been merged into `develop`. Close this issue.
