### ISSUE TITLE
[TASK] Story #33: Filtering GET /api/v1/listing results (3) - Keywords

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#142]
### Associated User Story: 
#33

### Task Description:
- This task aims to add the filtering functionality for `GET /api/v1/listing` route. 
- This task focuses on the following fields:
   - [x] title
   - [ ] description
- Subtasks:
   - [x] Add `validateQueryString` middleware which would validate & transform the query string into a json object (or any other format TBD) before being used by the `getAllListings` in ListingController.
   - [x] Update `getAllListings` in ListingController such that it passes query string to ListingService.
   - [x] (Optional) Validate the transformed query string in Service layer to ensure we're querying DB in DAO layer using valid query string.
   - [x] Update `getAllListings()` in ListingDao to ask DB do filtering for us via SQL queries.

### Dependencies:
- #140 (Filtering GET /api/v1/listing results (1) - Ranges)
- #141 (Filtering GET /api/v1/listing results (2) - Boolean)

### Acceptance Criteria:
- [x] Able to filter listings via keywords correctly when adding query string to the `GET /api/v1/listing` request.
- [x] Able to filter listings via the combination of keywords & all previously implemented fields correctly when adding query string to the `GET /api/v1/listing` request.

**Comment by jcsnorlax97** [comment]
Associated PR has been merged into `develop`. Close this issue.
(Note: only search the given keywords in listing `title` at the moment, i.e. listing `description` would not be considered for now.)
