### ISSUE TITLE
[TASK] Backend Server Setup for Deployment into Heroku 

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#78]
### Associated User Story: 
N/A

### Task Description:

- [X] Heroku
   - [X] Create new account
   - [X] Create new Heroku app in DashBoard.
   - [X] Add "Heroku Postgres" add-ons in the app->Resources tab.
   - [X] Update Config Vars in <app_page>->"Settings" tab by adding `DB_ENVIRONMENT=production` in it.
- [X] Rentr Project (Back-end)
   - [X] Add `npm start` script in `package.json` (Required by Heroku for running the app)
   - [X] Update `config/config.js` and `db/db.js` to handle DB in Production environment.
   - [X] Deploy Node.JS app (`/server` folder) & current feature branch into Heroku for first-try.

- Note: Before the end of this sprint, the Node.JS app (`/server` folder) & `master` branch need to be deployed into the Heroku as Prod. This would be done after `develop` has been merged into `master`. As no code changes involved to do that,  no tickets would be created for that.

### Dependencies:
Heroku

### Acceptance Criteria:
- Able to call the API locally, i.e. `localhost`
- Able to call the API via the given domain name by Heroku.

**Comment by jcsnorlax97** [comment]
PR is merged. Close this issue.
