### ISSUE TITLE
[TASK] Cleaning up naming conventions & Update Listing entity table

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#81]
### Associated User Story: 
N/A

### Task Description:

- [X] Rename `getUser()` to be `getUserViaId()` in UserController & UserDao & all associated test files.
- [X] Rename `getListing()` to be `getListingViaId()`
- [X] Rename `unAuthenticated()` to be `unauthenticated()`
- [X] Replace `res.status(401).json(...)` in `authenticateUser()` in `UserController` with `ApiError.unauthenticated(...)`
- [X] Ensure the following attributes are in the "Listing" entity in `init.sql`:
   - [X] listing id (int) — `id`
   - [X] Title (String; < 100 chars) — `title` 
   - [X] Price (String) — `price`
   - [X] Number of bedrooms (String) — `num_bedroom`
   - [X] Number of washrooms (String) — `num_bathroom`
   - [X] Laundry Room? (Boolean) — `is_laundry_available`
   - [X] Pet Allowed? (Boolean) — `is_pet_allowed`
   - [X] Parking Available? (Boolean) — `is_parking_available`
   - [X] Image (Url/Base64) (Array of String) — `images`
   - [X] Description (String; < 5000 chars) — `description`
- [X] Update all places that uses "Listing" entity and is affected: 
   - [X] Update `services/listing.js`
   - [X] Update `services/listing.test.js`
   - [X] Update `dto/listing.js`
   - [X] Update `dao/listing.js`
- [X] Ensure all API endpoints are working via Postman (See Screenshots Below):
   - [X] GET `/api/v1/ping` 
   - [X] GET `/api/v1/user/:id`
   - [X] POST `/api/v1/user/registration` 
   - [X] POST `/api/v1/user/login` 
   - [X] GET `/api/v1/listing`
   - [X] GET `/api/v1/listing/:id`
   - [X] POST `/api/v1/listing`
- [X] Environment variable, JWT_KEY, for authentication
   - [X] Decide shared secret key & initial user password
   - [X] Re-generate the hashed password used in `init.sql` & Update them
   - [X] Update `.env.template` as documentations

### Dependencies:
All Sprint 2 Dev Tasks

### Acceptance Criteria:
N/A

**Comment by jcsnorlax97** [comment]
PR is approved & merged. Close this issue.
